<?php

/**
 * Submission-timing spam check (LP-025): a form submitted implausibly fast is treated as automated.
 *
 * @package LumoraPress
 * @subpackage Security
 * @author Ariane
 * @copyright Copyright (c) 2026 Ariane
 * @license GPL-3.0-or-later
 * @link https://coding.unloved-heart.net/scripts/lumorapress
 * @source https://github.com/intothisshadow/LumoraPress
 * @since 0.5.0
 */

declare(strict_types=1);

namespace LumoraPress\Core\Security;

/**
 * Submission-timing check (LP-025): a real visitor takes at least a few
 * seconds to fill in a form, so an instant submission is a strong bot
 * signal — this is the "reject forms submitted too quickly" layer,
 * complementary to the honeypot field already used alongside it.
 *
 * Signed with the install's `secret_key` (config/config.php, generated by
 * the installer, otherwise unused) rather than stored in the session like
 * `Csrf` — this keeps a single render timestamp valid across the honeypot,
 * CSRF, and Akismet checks it sits alongside without needing its own
 * session bookkeeping. The HMAC only proves the timestamp wasn't tampered
 * with; `Csrf`'s per-action token is still what proves the request itself
 * is genuine.
 *
 * `setSecretKey()` is called once from include/bootstrap.php, mirroring
 * `ActiveTheme::set()`'s "wire a global once at boot" pattern — the
 * alternative (threading the secret key through every template that
 * renders a form) would be needless plumbing for a value that never
 * changes per-request.
 */
final class FormTiming
{
    private static ?string $secretKey = null;

    public static function setSecretKey(string $key): void
    {
        self::$secretKey = $key;
    }

    public static function field(): string
    {
        $time = (string) time();

        return '<input type="hidden" name="form_time" value="' . htmlspecialchars($time, ENT_QUOTES, 'UTF-8') . '">'
            . '<input type="hidden" name="form_time_hmac" value="' . htmlspecialchars(self::sign($time), ENT_QUOTES, 'UTF-8') . '">';
    }

    public static function verify(?string $time, ?string $hmac, int $minSeconds = 3): bool
    {
        if ($time === null || $hmac === null || !ctype_digit($time)) {
            return false;
        }

        if (!hash_equals(self::sign($time), $hmac)) {
            return false;
        }

        return (time() - (int) $time) >= $minSeconds;
    }

    private static function sign(string $time): string
    {
        return hash_hmac('sha256', $time, self::$secretKey ?? '');
    }
}
