<?php

/**
 * Writes a WordPress eXtended RSS (WXR) export, importable into WordPress or any other platform that reads WXR.
 *
 * @package LumoraPress
 * @subpackage Services
 * @author Ariane
 * @copyright Copyright (c) 2026 Ariane
 * @license GPL-3.0-or-later
 * @link https://coding.unloved-heart.net/scripts/lumorapress
 * @source https://github.com/intothisshadow/LumoraPress
 * @since 0.19.0
 */

declare(strict_types=1);

namespace LumoraPress\Services\Export;

use DateTimeImmutable;
use DateTimeZone;
use LumoraPress\Models\CommentStatus;
use LumoraPress\Models\ContentFormat;
use LumoraPress\Models\PageStatus;
use LumoraPress\Models\PageVisibility;
use LumoraPress\Models\PostStatus;
use LumoraPress\Models\PostVisibility;
use LumoraPress\Services\ContentRenderer;
use LumoraPress\Services\Import\ImportedMedia;
use LumoraPress\Services\Import\ImportedPage;
use LumoraPress\Services\Import\ImportedPost;
use RuntimeException;
use XMLWriter;

/**
 * Produces the same element shapes the WordPress Importer plugin's own
 * WXR reader parses, so this app can read back what it writes.
 *
 * WordPress keeps attachments, pages, posts, and menu items in one id
 * space (and categories, tags, and menus in another), where Lumora Press
 * has a table each — so each type gets its own id offset here to keep
 * every WXR id unique. Like a real WordPress export, attachments are
 * referenced by URL rather than bundled, and anything WXR has no slot for
 * is left out and reported through notices() instead of forced into an
 * ill-fitting field.
 */
final class WordPressXmlWriter implements ExportFormatWriter
{
    public const ID = 'wxr';

    private const WXR_VERSION = '1.2';

    /** @var array<int, string> */
    private array $notices = [];

    public function __construct(
        private readonly ContentRenderer $renderer,
        private readonly string $workingDirectory,
    ) {
    }

    public function id(): string
    {
        return self::ID;
    }

    public function label(): string
    {
        return 'WordPress WXR (.xml)';
    }

    public function description(): string
    {
        return "For moving your content to WordPress, or any other platform that reads WordPress's export format. Some Lumora Press-only details can't be carried over; you'll see a list after the export.";
    }

    public function supportedContentTypes(): array
    {
        return [
            ExportOptions::POSTS,
            ExportOptions::PAGES,
            ExportOptions::USERS,
            ExportOptions::MEDIA,
            ExportOptions::COMMENTS,
            ExportOptions::MENUS,
        ];
    }

    public function bundlesUploads(): bool
    {
        return false;
    }

    public function mimeType(): string
    {
        return 'application/xml';
    }

    public function downloadFileName(ExportContent $content): string
    {
        // Mirrors WordPress's own "{site}.WordPress.{date}.xml" naming.
        return $content->siteSlug() . '.WordPress.' . $content->exportedAt->format('Y-m-d') . '.xml';
    }

    public function write(ExportContent $content, ExportOptions $options): string
    {
        $this->notices = [];

        if (!is_dir($this->workingDirectory) && !mkdir($this->workingDirectory, 0755, true) && !is_dir($this->workingDirectory)) {
            throw new RuntimeException('Unable to create the export directory.');
        }

        $path = rtrim($this->workingDirectory, '/') . '/' . bin2hex(random_bytes(16)) . '.xml';
        $xml = new XMLWriter();

        if (!$xml->openUri($path)) {
            throw new RuntimeException('Unable to create the export file.');
        }

        $ids = $this->idMaps($content);
        $logins = [];

        foreach ($content->users as $user) {
            $logins[(int) $user->externalId] = $user->username;
        }

        $xml->setIndent(true);
        $xml->setIndentString("\t");
        $xml->startDocument('1.0', 'UTF-8');
        $xml->writeComment(' This is a WordPress eXtended RSS file generated by Lumora Press as an export of your site. ');
        $xml->startElement('rss');
        $xml->writeAttribute('version', '2.0');
        $xml->writeAttribute('xmlns:excerpt', 'http://wordpress.org/export/' . self::WXR_VERSION . '/excerpt/');
        $xml->writeAttribute('xmlns:content', 'http://purl.org/rss/1.0/modules/content/');
        $xml->writeAttribute('xmlns:wfw', 'http://wellformedweb.org/CommentAPI/');
        $xml->writeAttribute('xmlns:dc', 'http://purl.org/dc/elements/1.1/');
        $xml->writeAttribute('xmlns:wp', 'http://wordpress.org/export/' . self::WXR_VERSION . '/');
        $xml->startElement('channel');

        $xml->writeElement('title', self::clean($content->siteName));
        $xml->writeElement('link', $content->siteUrl);
        $xml->writeElement('description', '');
        $xml->writeElement('pubDate', $content->exportedAt->format(DATE_RSS));
        $xml->writeElement('wp:wxr_version', self::WXR_VERSION);
        $xml->writeElement('wp:base_site_url', $content->siteUrl);
        $xml->writeElement('wp:base_blog_url', $content->siteUrl);

        $this->writeAuthors($xml, $content);
        $this->writeTerms($xml, $content, $ids);
        $xml->writeElement('generator', 'Lumora Press/' . $content->generatorVersion);

        foreach ($content->media as $media) {
            $this->writeAttachment($xml, $content, $media, $ids, $logins);
        }

        foreach ($content->pages as $page) {
            $this->writePage($xml, $content, $page, $ids, $logins);
        }

        foreach ($content->posts as $post) {
            $this->writePost($xml, $content, $post, $ids, $logins);
        }

        $this->writeMenuItems($xml, $content, $ids);

        $xml->endElement();
        $xml->endElement();
        $xml->endDocument();
        $xml->flush();

        $this->collectNotices($content);

        return $path;
    }

    public function notices(): array
    {
        return $this->notices;
    }

    /**
     * @return array{media: int, page: int, post: int, menuItem: int, tag: int, menu: int, categorySlugs: array<int, string>, tagSlugsByName: array<string, string>, menuSlugs: array<string, string>}
     */
    private function idMaps(ExportContent $content): array
    {
        $maxId = static fn (array $values): int => $values === [] ? 0 : max($values);
        $pageOffset = $maxId(array_map(static fn (ImportedMedia $media): int => (int) $media->externalId, $content->media));
        $postOffset = $pageOffset + $maxId(array_map(static fn (ImportedPage $page): int => (int) $page->externalId, $content->pages));
        $menuItemOffset = $postOffset + $maxId(array_map(static fn (ImportedPost $post): int => (int) $post->externalId, $content->posts));
        $tagOffset = $maxId(array_column($content->categories, 'id'));
        $menuOffset = $tagOffset + $maxId(array_column($content->tags, 'id'));

        $categorySlugs = [];

        foreach ($content->categories as $category) {
            $categorySlugs[$category['id']] = $category['slug'];
        }

        $tagSlugsByName = [];

        foreach ($content->tags as $tag) {
            $tagSlugsByName[mb_strtolower($tag['name'])] = $tag['slug'];
        }

        $menuSlugs = [];
        $usedSlugs = [];

        foreach ($content->menus as $menu) {
            $base = self::slugify($menu->name) ?: 'menu';
            $slug = $base;

            for ($suffix = 2; isset($usedSlugs[$slug]); $suffix++) {
                $slug = $base . '-' . $suffix;
            }

            $usedSlugs[$slug] = true;
            $menuSlugs[(string) $menu->externalId] = $slug;
        }

        return [
            'media' => 0,
            'page' => $pageOffset,
            'post' => $postOffset,
            'menuItem' => $menuItemOffset,
            'tag' => $tagOffset,
            'menu' => $menuOffset,
            'categorySlugs' => $categorySlugs,
            'tagSlugsByName' => $tagSlugsByName,
            'menuSlugs' => $menuSlugs,
        ];
    }

    private function writeAuthors(XMLWriter $xml, ExportContent $content): void
    {
        foreach ($content->users as $user) {
            $xml->startElement('wp:author');
            $xml->writeElement('wp:author_id', (string) (int) $user->externalId);
            self::cdata($xml, 'wp:author_login', $user->username);
            self::cdata($xml, 'wp:author_email', $user->email);
            self::cdata($xml, 'wp:author_display_name', $user->displayName ?? $user->username);
            self::cdata($xml, 'wp:author_first_name', '');
            self::cdata($xml, 'wp:author_last_name', '');
            $xml->endElement();
        }
    }

    /**
     * @param array{media: int, page: int, post: int, menuItem: int, tag: int, menu: int, categorySlugs: array<int, string>, tagSlugsByName: array<string, string>, menuSlugs: array<string, string>} $ids
     */
    private function writeTerms(XMLWriter $xml, ExportContent $content, array $ids): void
    {
        foreach ($content->categories as $category) {
            $xml->startElement('wp:category');
            $xml->writeElement('wp:term_id', (string) $category['id']);
            self::cdata($xml, 'wp:category_nicename', $category['slug']);
            self::cdata($xml, 'wp:category_parent', $category['parentId'] !== null ? ($ids['categorySlugs'][$category['parentId']] ?? '') : '');
            self::cdata($xml, 'wp:cat_name', $category['name']);
            self::cdata($xml, 'wp:category_description', $category['description']);
            $xml->endElement();
        }

        foreach ($content->tags as $tag) {
            $xml->startElement('wp:tag');
            $xml->writeElement('wp:term_id', (string) ($ids['tag'] + $tag['id']));
            self::cdata($xml, 'wp:tag_slug', $tag['slug']);
            self::cdata($xml, 'wp:tag_name', $tag['name']);
            self::cdata($xml, 'wp:tag_description', $tag['description']);
            $xml->endElement();
        }

        foreach (array_values($content->menus) as $index => $menu) {
            $xml->startElement('wp:term');
            $xml->writeElement('wp:term_id', (string) ($ids['menu'] + $index + 1));
            self::cdata($xml, 'wp:term_taxonomy', 'nav_menu');
            self::cdata($xml, 'wp:term_slug', $ids['menuSlugs'][(string) $menu->externalId]);
            self::cdata($xml, 'wp:term_parent', '');
            self::cdata($xml, 'wp:term_name', $menu->name);
            $xml->endElement();
        }
    }

    /**
     * @param array{media: int, page: int, post: int, menuItem: int, tag: int, menu: int, categorySlugs: array<int, string>, tagSlugsByName: array<string, string>, menuSlugs: array<string, string>} $ids
     * @param array<int, string> $logins
     */
    private function writeAttachment(XMLWriter $xml, ExportContent $content, ImportedMedia $media, array $ids, array $logins): void
    {
        $filePath = $content->mediaFiles[(int) $media->externalId]['filePath'] ?? '';
        $url = self::absoluteUrl($content, $content->uploadsUrl . '/' . $filePath);
        $name = pathinfo($media->fileName ?? basename($filePath), PATHINFO_FILENAME);

        $this->startItem($xml, [
            'id' => $ids['media'] + (int) $media->externalId,
            'title' => $name,
            'link' => $url,
            'guid' => $url,
            'author' => $logins[$media->uploadedByUserId] ?? '',
            'content' => $media->description ?? '',
            'excerpt' => $media->caption ?? '',
            'date' => $media->uploadedAt ?? $content->exportedAt,
            'published' => true,
            'commentStatus' => 'closed',
            'slug' => self::slugify($name),
            'status' => 'inherit',
            'parent' => 0,
            'menuOrder' => 0,
            'type' => 'attachment',
            'sticky' => false,
        ]);
        $xml->writeElement('wp:attachment_url', $url);
        self::postmeta($xml, '_wp_attached_file', $filePath);

        if (($media->altText ?? '') !== '') {
            self::postmeta($xml, '_wp_attachment_image_alt', (string) $media->altText);
        }

        $xml->endElement();
    }

    /**
     * @param array{media: int, page: int, post: int, menuItem: int, tag: int, menu: int, categorySlugs: array<int, string>, tagSlugsByName: array<string, string>, menuSlugs: array<string, string>} $ids
     * @param array<int, string> $logins
     */
    private function writePage(XMLWriter $xml, ExportContent $content, ImportedPage $page, array $ids, array $logins): void
    {
        $wxrId = $ids['page'] + (int) $page->externalId;

        $this->startItem($xml, [
            'id' => $wxrId,
            'title' => $page->title,
            'link' => $content->siteUrl . '/?page_id=' . $wxrId,
            'guid' => $content->siteUrl . '/?page_id=' . $wxrId,
            'author' => $logins[$page->authorId] ?? '',
            'content' => $this->html($page->content, $page->contentFormat),
            'excerpt' => $page->excerpt,
            'date' => $page->publishedAt ?? $content->exportedAt,
            'published' => $page->publishedAt !== null,
            'commentStatus' => ($page->commentsOpen ?? true) ? 'open' : 'closed',
            'slug' => $page->slug ?? '',
            'status' => self::wxrStatus($page->status === PageStatus::Published, $page->status->value, $page->visibility === PageVisibility::Private),
            'parent' => $page->parentExternalId !== null ? $ids['page'] + (int) $page->parentExternalId : 0,
            'menuOrder' => 0,
            'type' => 'page',
            'sticky' => false,
        ]);
        $this->writeFeaturedImage($xml, $content, $page->featuredImageId, $ids);
        $this->writeComments($xml, $content, null, (int) $page->externalId);
        $xml->endElement();
    }

    /**
     * @param array{media: int, page: int, post: int, menuItem: int, tag: int, menu: int, categorySlugs: array<int, string>, tagSlugsByName: array<string, string>, menuSlugs: array<string, string>} $ids
     * @param array<int, string> $logins
     */
    private function writePost(XMLWriter $xml, ExportContent $content, ImportedPost $post, array $ids, array $logins): void
    {
        $wxrId = $ids['post'] + (int) $post->externalId;

        $this->startItem($xml, [
            'id' => $wxrId,
            'title' => $post->title,
            'link' => $content->siteUrl . '/?p=' . $wxrId,
            'guid' => $content->siteUrl . '/?p=' . $wxrId,
            'author' => $logins[$post->authorId] ?? '',
            'content' => $this->html($post->content, $post->contentFormat),
            'excerpt' => $post->excerpt,
            'date' => $post->publishedAt ?? $content->exportedAt,
            'published' => $post->publishedAt !== null,
            'commentStatus' => $post->commentsOpen ? 'open' : 'closed',
            'slug' => $post->slug ?? '',
            'status' => self::wxrStatus($post->status === PostStatus::Published, $post->status->value, $post->visibility === PostVisibility::Private),
            'parent' => 0,
            'menuOrder' => 0,
            'type' => 'post',
            'sticky' => $post->isSticky,
        ]);

        $categoryIds = $post->categoryIds;

        foreach ($categoryIds as $index => $categoryId) {
            $name = $post->categories[$index] ?? null;
            $slug = $ids['categorySlugs'][$categoryId] ?? null;

            if ($name !== null && $slug !== null) {
                self::category($xml, 'category', $slug, $name);
            }
        }

        if ($categoryIds === []) {
            foreach ($post->categories as $name) {
                self::category($xml, 'category', self::slugify($name), $name);
            }
        }

        foreach ($post->tags as $name) {
            self::category($xml, 'post_tag', $ids['tagSlugsByName'][mb_strtolower($name)] ?? self::slugify($name), $name);
        }

        foreach ($post->meta as $pair) {
            self::postmeta($xml, $pair['key'], $pair['value']);
        }

        $this->writeFeaturedImage($xml, $content, $post->featuredImageId, $ids);
        $this->writeComments($xml, $content, (int) $post->externalId, null);
        $xml->endElement();
    }

    /**
     * WordPress menus hold menu items as posts; every Lumora Press menu
     * item is a plain label + address, so each becomes a "custom" link.
     *
     * @param array{media: int, page: int, post: int, menuItem: int, tag: int, menu: int, categorySlugs: array<int, string>, tagSlugsByName: array<string, string>, menuSlugs: array<string, string>} $ids
     */
    private function writeMenuItems(XMLWriter $xml, ExportContent $content, array $ids): void
    {
        $nextId = $ids['menuItem'];

        foreach ($content->menus as $menu) {
            $wxrIdByItemId = [];

            foreach ($menu->items as $item) {
                $wxrIdByItemId[(string) $item->externalId] = ++$nextId;
            }

            foreach ($menu->items as $item) {
                $wxrId = $wxrIdByItemId[(string) $item->externalId];

                $this->startItem($xml, [
                    'id' => $wxrId,
                    'title' => $item->label,
                    'link' => $content->siteUrl . '/?p=' . $wxrId,
                    'guid' => $content->siteUrl . '/?p=' . $wxrId,
                    'author' => '',
                    'content' => '',
                    'excerpt' => '',
                    'date' => $content->exportedAt,
                    'published' => true,
                    'commentStatus' => 'closed',
                    'slug' => (string) $wxrId,
                    'status' => 'publish',
                    'parent' => 0,
                    'menuOrder' => $item->order + 1,
                    'type' => 'nav_menu_item',
                    'sticky' => false,
                ]);
                self::category($xml, 'nav_menu', $ids['menuSlugs'][(string) $menu->externalId], $menu->name);
                self::postmeta($xml, '_menu_item_type', 'custom');
                self::postmeta($xml, '_menu_item_menu_item_parent', (string) ($item->parentExternalId !== null ? ($wxrIdByItemId[$item->parentExternalId] ?? 0) : 0));
                self::postmeta($xml, '_menu_item_object_id', (string) $wxrId);
                self::postmeta($xml, '_menu_item_object', 'custom');
                self::postmeta($xml, '_menu_item_target', $item->target === '_blank' ? '_blank' : '');
                self::postmeta($xml, '_menu_item_classes', serialize($item->cssClass !== '' ? preg_split('/\s+/', trim($item->cssClass)) : ['']));
                self::postmeta($xml, '_menu_item_xfn', $item->rel);
                self::postmeta($xml, '_menu_item_url', self::absoluteUrl($content, $item->url));
                $xml->endElement();
            }
        }
    }

    /**
     * @param array{media: int, page: int, post: int, menuItem: int, tag: int, menu: int, categorySlugs: array<int, string>, tagSlugsByName: array<string, string>, menuSlugs: array<string, string>} $ids
     */
    private function writeFeaturedImage(XMLWriter $xml, ExportContent $content, ?int $featuredImageId, array $ids): void
    {
        if ($featuredImageId !== null && isset($content->mediaFiles[$featuredImageId])) {
            self::postmeta($xml, '_thumbnail_id', (string) ($ids['media'] + $featuredImageId));
        }
    }

    private function writeComments(XMLWriter $xml, ExportContent $content, ?int $postId, ?int $pageId): void
    {
        foreach ($content->comments as $comment) {
            $belongs = $postId !== null ? $comment->postId === $postId : $comment->pageId === $pageId;

            if (!$belongs) {
                continue;
            }

            $date = $comment->commentedAt ?? $content->exportedAt;

            $xml->startElement('wp:comment');
            $xml->writeElement('wp:comment_id', (string) (int) $comment->externalId);
            self::cdata($xml, 'wp:comment_author', $comment->guestName);
            self::cdata($xml, 'wp:comment_author_email', $comment->guestEmail);
            $xml->writeElement('wp:comment_author_url', self::clean($comment->guestUrl ?? ''));
            self::cdata($xml, 'wp:comment_author_IP', '');
            $xml->writeElement('wp:comment_date', $date->format('Y-m-d H:i:s'));
            $xml->writeElement('wp:comment_date_gmt', $date->setTimezone(new DateTimeZone('UTC'))->format('Y-m-d H:i:s'));
            self::cdata($xml, 'wp:comment_content', $comment->content);
            self::cdata($xml, 'wp:comment_approved', match ($comment->status) {
                CommentStatus::Approved => '1',
                CommentStatus::Spam => 'spam',
                CommentStatus::Trash => 'trash',
                CommentStatus::Pending => '0',
            });
            self::cdata($xml, 'wp:comment_type', 'comment');
            $xml->writeElement('wp:comment_parent', (string) (int) ($comment->parentExternalId ?? 0));
            $xml->writeElement('wp:comment_user_id', (string) ($comment->userId ?? 0));
            $xml->endElement();
        }
    }

    /**
     * Opens an <item> and writes the fields every WXR post type shares;
     * the caller adds its own extras and closes the element.
     *
     * @param array{id: int, title: string, link: string, guid: string, author: string, content: string, excerpt: string, date: DateTimeImmutable, published: bool, commentStatus: string, slug: string, status: string, parent: int, menuOrder: int, type: string, sticky: bool} $item
     */
    private function startItem(XMLWriter $xml, array $item): void
    {
        $xml->startElement('item');
        self::cdata($xml, 'title', $item['title']);
        $xml->writeElement('link', self::clean($item['link']));
        $xml->writeElement('pubDate', $item['published'] ? $item['date']->format(DATE_RSS) : '');
        self::cdata($xml, 'dc:creator', $item['author']);
        $xml->startElement('guid');
        $xml->writeAttribute('isPermaLink', 'false');
        $xml->text(self::clean($item['guid']));
        $xml->endElement();
        $xml->writeElement('description', '');
        self::cdata($xml, 'content:encoded', $item['content']);
        self::cdata($xml, 'excerpt:encoded', $item['excerpt']);
        $xml->writeElement('wp:post_id', (string) $item['id']);
        self::cdata($xml, 'wp:post_date', $item['date']->format('Y-m-d H:i:s'));
        self::cdata($xml, 'wp:post_date_gmt', $item['published'] ? $item['date']->setTimezone(new DateTimeZone('UTC'))->format('Y-m-d H:i:s') : '0000-00-00 00:00:00');
        self::cdata($xml, 'wp:comment_status', $item['commentStatus']);
        self::cdata($xml, 'wp:ping_status', 'closed');
        self::cdata($xml, 'wp:post_name', $item['slug']);
        self::cdata($xml, 'wp:status', $item['status']);
        $xml->writeElement('wp:post_parent', (string) $item['parent']);
        $xml->writeElement('wp:menu_order', (string) $item['menuOrder']);
        self::cdata($xml, 'wp:post_type', $item['type']);
        self::cdata($xml, 'wp:post_password', '');
        $xml->writeElement('wp:is_sticky', $item['sticky'] ? '1' : '0');
    }

    /**
     * WordPress has no Markdown, so Markdown is converted to HTML here.
     * Deliberately not ContentRenderer::render(): that also expands
     * shortcodes and embeds, and WordPress should receive the shortcodes
     * themselves (many have direct WordPress equivalents).
     */
    private function html(string $content, ContentFormat $format): string
    {
        return match ($format) {
            ContentFormat::Html => $content,
            ContentFormat::Markdown => $this->renderer->convertFormat($content, ContentFormat::Markdown, ContentFormat::Html),
            ContentFormat::Plain => nl2br(htmlspecialchars($content, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8')),
        };
    }

    private function collectNotices(ExportContent $content): void
    {
        $seoCount = 0;
        $cropCount = 0;
        $markdownCount = 0;
        $unpublishCount = 0;
        $missingFeaturedImages = 0;

        foreach ([...$content->posts, ...$content->pages] as $item) {
            $seoCount += ($item->metaTitle !== null || $item->metaDescription !== null) ? 1 : 0;
            $cropCount += $item->featuredImageCrop !== null ? 1 : 0;
            $markdownCount += $item->contentFormat === ContentFormat::Markdown ? 1 : 0;
            $unpublishCount += $item instanceof ImportedPost && $item->unpublishAt !== null ? 1 : 0;
            $missingFeaturedImages += $item->featuredImageId !== null && !isset($content->mediaFiles[$item->featuredImageId]) ? 1 : 0;
        }

        $categoryExtras = count(array_filter($content->categories, static fn (array $category): bool => $category['imageId'] !== null || $category['archiveDisplayMode'] !== null));

        $notes = [
            [$seoCount, 'SEO title/description override', 'WordPress has no built-in field for these'],
            [$cropCount, 'featured image crop', 'the full, uncropped image is used instead'],
            [$unpublishCount, 'scheduled unpublish date', 'WordPress has no automatic unpublishing'],
            [$categoryExtras, 'category image or archive layout setting', 'WordPress categories have no such fields'],
            [count($content->folders), 'media folder', 'WordPress has no media folders; every file is exported, just not organized into folders'],
            [$missingFeaturedImages, 'featured image', 'Media wasn\'t included in this export, so there was no image to point to'],
        ];

        foreach ($notes as [$count, $what, $why]) {
            if ($count > 0) {
                $this->notices[] = "{$count} {$what}" . ($count === 1 ? '' : 's') . " left out — {$why}.";
            }
        }

        if ($content->users !== []) {
            $this->notices[] = 'User roles left out — the format has no field for them, so every user arrives with the importing site\'s default role.';
        }

        if ($content->menuLocations !== []) {
            $this->notices[] = 'Menu locations left out — menus are exported, but need to be assigned to your new theme\'s locations again.';
        }

        if ($markdownCount > 0) {
            $this->notices[] = "{$markdownCount} post" . ($markdownCount === 1 ? '' : 's') . '/page' . ($markdownCount === 1 ? '' : 's') . ' written in Markdown ' . ($markdownCount === 1 ? 'was' : 'were') . ' converted to HTML.';
        }
    }

    private static function wxrStatus(bool $isPublished, string $status, bool $isPrivate): string
    {
        if ($isPublished && $isPrivate) {
            return 'private';
        }

        return match ($status) {
            'published' => 'publish',
            'scheduled' => 'future',
            'pending_review' => 'pending',
            default => 'draft',
        };
    }

    private static function category(XMLWriter $xml, string $domain, string $slug, string $name): void
    {
        $xml->startElement('category');
        $xml->writeAttribute('domain', $domain);
        $xml->writeAttribute('nicename', self::clean($slug));
        $xml->writeRaw(self::cdataBlock($name));
        $xml->endElement();
    }

    private static function postmeta(XMLWriter $xml, string $key, string $value): void
    {
        $xml->startElement('wp:postmeta');
        self::cdata($xml, 'wp:meta_key', $key);
        self::cdata($xml, 'wp:meta_value', $value);
        $xml->endElement();
    }

    private static function cdata(XMLWriter $xml, string $name, string $value): void
    {
        $xml->startElement($name);
        $xml->writeRaw(self::cdataBlock($value));
        $xml->endElement();
    }

    /**
     * Same "]]>" splitting WordPress's own exporter uses, so content that
     * happens to contain it can't end the CDATA section early.
     */
    private static function cdataBlock(string $value): string
    {
        return '<![CDATA[' . str_replace(']]>', ']]]]><![CDATA[>', self::clean($value)) . ']]>';
    }

    /**
     * Strips characters XML 1.0 forbids outright (stray control bytes in
     * old content would otherwise make the whole file unparseable).
     */
    private static function clean(string $value): string
    {
        if (!mb_check_encoding($value, 'UTF-8')) {
            $value = mb_convert_encoding($value, 'UTF-8', 'UTF-8');
        }

        return (string) preg_replace('/[^\x{9}\x{A}\x{D}\x{20}-\x{D7FF}\x{E000}-\x{FFFD}\x{10000}-\x{10FFFF}]/u', '', $value);
    }

    private static function absoluteUrl(ExportContent $content, string $url): string
    {
        if (preg_match('#^[a-z][a-z0-9+.-]*:#i', $url) === 1 || str_starts_with($url, '//')) {
            return $url;
        }

        $parts = parse_url($content->siteUrl);
        $origin = ($parts['scheme'] ?? 'https') . '://' . ($parts['host'] ?? '') . (isset($parts['port']) ? ':' . $parts['port'] : '');

        return str_starts_with($url, '/') ? $origin . $url : rtrim($content->siteUrl, '/') . '/' . $url;
    }

    private static function slugify(string $value): string
    {
        return trim((string) preg_replace('/[^a-z0-9]+/', '-', mb_strtolower($value)), '-');
    }
}
